name: GitHub Classroom Workflow

on:
  workflow_dispatch:
  push:
    paths_ignore:
      - '.github/*'

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  Checking-Solution:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

       - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install valgrind
          sudo apt-get install g++-11
          sudo apt-get install gcc-11
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 110
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110
          g++ --version
          gcc --version

      - name: Build
        run: |
          make
          if [ $? -ne 0 ]; then
            echo "Build failed!"
            exit 1
          fi
          !(grep -qwRE --include=*.{cc,cpp,h} '#include <(list|algorithm|stack|queue|deque|set|map)>' ./* ) &&  (echo \"Build...\" )  || ( echo \"Forbiden STL containers\" && exit 9 )
      
      - name: Static Analysis with clang-tidy
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug  # или Release, в зависимости от нужд
          cmake --build . --target all
          # Запуск clang-tidy, настраиваем пути к исходникам и параметры
          find . -name "*.cpp" -o -name "*.h" | while read file; do
            clang-tidy "$file" -checks=-*,modernize-*,cppcoreguidelines-* -header-filter=".*" -- -std=c++17
          done
          cd ..

      - name: Autograding
        uses: amcp-pit/autograding@v1

      - name: Memory leaks
        run: |
          valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./containers_app

      - name: Checkout
        uses: actions/checkout@v4
      - name: CPD
        uses: amcp-pit/cpd-action@v1
        id: cpd
        with:
          repository: ${{ github.repository }}
          collection: ${{ github.repository_owner }}

      - name: Clean
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
